// This file was auto-generated by ML.NET Model Builder. 

using System;
using SWE_ImageML.Model;

namespace SWE_ImageML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {

            Console.WriteLine("Enter path to image or exit");

            string path = "";
			while (true)
            {
                path = Console.ReadLine();

                if (path.StartsWith("exit"))
                    break;

                try
                {
                    // Create single instance of sample data from first line of dataset for model input
                    ModelInput sampleData = new ModelInput()
                    {
                        ImageSource = path,
                    };

                    // Make a single prediction on the sample data and print results
                    var predictionResult = ConsumeModel.Predict(sampleData);

                    Console.WriteLine("Using model to make single prediction -- Comparing actual Label with predicted Label from sample data...\n\n");
                    Console.WriteLine($"ImageSource: {sampleData.ImageSource}");
                    Console.WriteLine($"\n\nPredicted Label value {predictionResult.Prediction} \nPredicted Label scores: [{String.Join(",", predictionResult.Score)}]\n\n");
                }
                catch(Exception e)
				{
                    Console.WriteLine(e);
                    break;
				}
            }

        }
    }
}
